# =============================================================================
# Configuración de Hadolint (Dockerfile Linter)
# =============================================================================

# Reglas ignoradas
ignored:
  - DL3008   # Pin versions in apt-get install
  - DL3013   # Pin versions in pip
  - DL3015   # Avoid additional packages
  - DL3016   # Pin versions in npm
  - DL3018   # Pin versions in apk add
  - DL4001   # Either use Wget or Curl but not both
  - DL4006   # Set the SHELL option -o pipefail

# Reglas que son errores (no warnings)
override:
  error:
    - DL3000   # Use absolute WORKDIR
    - DL3001   # For some commands like ssh, wget, they require STDIN

# Registros de Docker confiables
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
